name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Thanks https://stackoverflow.com/questions/56506392/how-do-i-add-an-example-project-to-a-flutter-package !
dependencies:
  flutter:
    sdk: flutter

  flutter_parallax_transitions:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: false
