include: package:lint/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: true
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true

    file_names: false

    avoid_setters_without_getters: false

    sort_pub_dependencies: false

    prefer_relative_imports: true
    always_use_package_imports: false

    # only for debug
    avoid_print: false

    # TODO RESEARCH
    use_build_context_synchronously: false

    depend_on_referenced_packages: true
